"use client";

import { Button } from "@/components/ui/button";
import { CornerRightUp } from "lucide-react";
import { useState, useRef, useEffect, SetStateAction } from "react";
import { streamText, StreamResponse } from "@/utils/stream-text";
import { useChatStore } from "@/hooks/use-chat-store";
import { Input } from "@/components/ui/input";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { cn } from "@/lib/utils";
import { AIThinking } from "./AIThinking";

export function Chat() {
  const [message, setMessage] = useState("");
  const [streamingContent, setStreamingContent] = useState<StreamResponse | null>(null);
  const { messages, addMessage, isLoading, setIsLoading } = useChatStore();
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, streamingContent]);

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!message.trim() || isLoading) return;

    const userMessage = {
      id: Date.now().toString(),
      content: message,
      role: "user" as const,
      timestamp: new Date().toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
      }),
    };

    addMessage(userMessage);
    setMessage("");
    setIsLoading(true);
    let currentResponse = '';

    try {
      // Set initial thinking state
      setStreamingContent({
        type: 'thinking',
        content: 'Analyzing your request...',
        step: 'start'
      });

      for await (const chunk of streamText(message)) {
        setStreamingContent(chunk);
        if (chunk.type === 'message' || chunk.type === 'image') {
          currentResponse = chunk.content;
          // If it's an image response, include the image_url
          if (chunk.type === 'image' && chunk.image_url) {
            currentResponse = {
              content: chunk.content,
              image_url: chunk.image_url
            };
          }
        }
      }

      if (currentResponse) {
        addMessage({
          id: (Date.now() + 1).toString(),
          content: typeof currentResponse === 'string' ? currentResponse : currentResponse.content,
          image_url: typeof currentResponse === 'string' ? undefined : currentResponse.image_url,
          role: "assistant",
          timestamp: new Date().toLocaleTimeString([], {
            hour: "2-digit",
            minute: "2-digit",
          }),
        });
      }
    } catch (error) {
      console.error("Error in chat:", error);
      setStreamingContent({
        type: 'error',
        content: 'Failed to get response from the agent.',
      });
    } finally {
      setTimeout(() => {
        setIsLoading(false);
        setStreamingContent(null);
      }, 500);
    }
  };

  const renderStreamingContent = () => {
    if (!streamingContent) return null;

    return (
      <div className="flex items-start gap-3">
        <Avatar className="h-8 w-8 shrink-0">
          <AvatarImage src="/user-avatar.svg" />
          <AvatarFallback>C</AvatarFallback>
        </Avatar>
        <div className="grid gap-1 w-full">
          <div className="flex items-center gap-2">
            <span className="font-semibold text-foreground">CrypGod</span>
          </div>
          
          {streamingContent.type === 'thinking' && (
            <div className="flex items-center gap-2 text-muted-foreground">
              <AIThinking />
              <span>{streamingContent.content}</span>
            </div>
          )}

          {streamingContent.type === 'tool_usage' && (
            <div className="text-muted-foreground">
              <p>{streamingContent.content}</p>
              {streamingContent.details && (
                <p className="text-sm opacity-80">{streamingContent.details}</p>
              )}
            </div>
          )}

          {streamingContent.type === 'message' && (
            <div className="text-foreground">{streamingContent.content}</div>
          )}

          {streamingContent.type === 'image' && (
            <div className="grid gap-2">
              <div className="text-foreground">{streamingContent.content}</div>
              {streamingContent.image_url && (
                <img 
                  src={streamingContent.image_url} 
                  alt="Generated by DALLE-3"
                  className="rounded-lg max-w-full h-auto shadow-lg"
                />
              )}
            </div>
          )}

          {streamingContent.type === 'error' && (
            <div className="text-destructive">{streamingContent.content}</div>
          )}
        </div>
      </div>
    );
  };

  const renderMessage = (message: any) => (
    <div key={message.id} className="flex items-start gap-3">
      <Avatar className="h-8 w-8 shrink-0">
        <AvatarImage
          src={message.role === "user" ? "/user-avatar.svg" : "/user-avatar.svg"}
        />
        <AvatarFallback>{message.role === "user" ? "U" : "C"}</AvatarFallback>
      </Avatar>
      <div className="grid gap-1">
        <div className="flex items-center gap-2">
          <span className="font-semibold text-foreground">
            {message.role === "user" ? "You" : "CrypGod"}
          </span>
          <span className="text-xs text-muted-foreground">
            {message.timestamp}
          </span>
        </div>
        <div className={cn(
          "text-foreground",
          message.role === "assistant" && "prose prose-zinc dark:prose-invert max-w-none"
        )}>
          {message.content}
          {message.image_url && (
            <img 
              src={message.image_url} 
              alt="Generated by DALLE-3"
              className="mt-2 rounded-lg max-w-full h-auto shadow-lg"
            />
          )}
        </div>
      </div>
    </div>
  );

  return (
    <div className="flex flex-col bg-white border rounded-3xl h-[calc(90vh-40px)] dark:bg-neutral-900 dark:border-neutral-700">
      <div className="border-b p-4 flex items-center justify-between border-neutral-700">
        <h1 className="text-xl font-semibold">CrypGod</h1>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-6">
        {messages.map((msg) => renderMessage(msg))}
        {streamingContent && renderStreamingContent()}
        <div ref={messagesEndRef} />
      </div>

      <form onSubmit={handleSendMessage} className="p-4 border-t border-neutral-700">
        <div className="flex items-center gap-2">
          <Input
            value={message}
            onChange={(e: { target: { value: SetStateAction<string> } }) =>
              setMessage(e.target.value)
            }
            placeholder="Type a message..."
          />
          <Button
            type="submit"
            size="icon"
            disabled={isLoading}
            className="shrink-0 bg-white/5 py-1 px-1 hover:bg-white/10"
          >
            <CornerRightUp
              className={cn("w-4 h-4 transition-opacity dark:text-white", {
                "opacity-100": message,
                "opacity-30": !message,
              })}
            />
          </Button>
        </div>
      </form>
    </div>
  );
}
